class ValidationError(Exception):
    pass


class AlreadyExistException(Exception):
    pass
